#index:
#    path: /
#    controller: App\Controller\DefaultController::index

    
homepage:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage 
    defaults:
      _locale: en  
    requirements:
      _locale: 'en|fr' 
    
add_product:
    path: /{_locale}/add/product
    controller: App\Controller\ProductController::addProduct
    requirements:
      _locale: 'en|fr' 

add_user:
    path: /{_locale}/add/user
    controller: App\Controller\UserController::register 
    requirements:
      _locale: 'en|fr' 
        
user_activate: 
    path: /{_locale}/user/activate/{token}
    controller: App\Controller\UserController::activateUser
    defaults:
        _locale: en
    requirements:
        token: '[a-z0-9-]+'
        _locale: 'en|fr' 
        
product_display:
    path: /{_locale}/products
    controller: App\Controller\ProductController::displayProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'        

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable   
    methods: ['POST']
    
  
